# Generated by Django 2.0.4 on 2018-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='username',
            field=models.TextField(blank=True),
        ),
    ]
