# Generated by Django 2.0.4 on 2018-04-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0002_tweets_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='username',
        ),
    ]
