# Generated by Django 2.0.4 on 2018-04-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0003_remove_tweets_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_model_cyberbullying_json', models.TextField(blank=True)),
                ('affective_counts_cyberbullying_json', models.TextField(blank=True)),
            ],
        ),
    ]
