# Generated by Django 2.0.4 on 2018-04-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0004_mlcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlcache',
            name='topic_model_cyberbullying_json',
        ),
    ]
