# Generated by Django 2.0.4 on 2018-04-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0005_remove_mlcache_topic_model_cyberbullying_json'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweets1',
        ),
    ]
