# Generated by Django 2.0.4 on 2018-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0006_auto_20180425_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=280)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tweets1',
            new_name='Tweets',
        ),
    ]
