# Generated by Django 2.0.4 on 2018-04-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0007_auto_20180425_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
