# Generated by Django 2.0.4 on 2018-04-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0008_delete_tweets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets2',
            new_name='Tweets',
        ),
    ]
