# Generated by Django 2.0.4 on 2018-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0009_auto_20180425_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='cleanMessage',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
