# Generated by Django 2.0.4 on 2018-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0011_cleanmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanmessage',
            old_name='cleanmessage',
            new_name='false_negatives',
        ),
        migrations.AddField(
            model_name='cleanmessage',
            name='false_positives',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cleanmessage',
            name='precision',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cleanmessage',
            name='recall',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cleanmessage',
            name='true_negatives',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cleanmessage',
            name='true_positives',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
