# Generated by Django 2.0.4 on 2018-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_project', '0013_cleanmessage_totaltweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanmessage',
            name='fScore',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
